class ArabicStrings {
  static Map<String, String> get arabicStrings => {
    'home': 'الرئيسية',
    'tasks': 'المهام',
    'market': 'المتجر',
    'farm': 'مزرعتي',
    'wallet': 'المحفظة',
    'referral': 'الإحالة',
    'login': 'تسجيل الدخول',
    'signup': 'إنشاء حساب',
    'logout': 'تسجيل الخروج',
    'points': 'ITC',
    'dailyLogin': 'تسجيل الدخول اليومي',
    'loginStreak': 'عدد مرات تسجيل الدخول المتتالي',
    'tasksAvailable': 'المهام المتاحة',
    'visitWebsites': 'زيارة المواقع',
    'downloadApps': 'تحميل التطبيقات',
    'completeSurveys': 'إنهاء الاستطلاعات',
    'watchAds': 'مشاهدة الإعلانات',
    'visitSocial': 'متابعة الحسابات الاجتماعية',
    'visitSite': 'زيارة الموقع',
    'collect': 'جمع',
    'buy': 'شراء',
    'deposit': 'ادخل رصيدك',
    'myFarm': 'مزرعتي',
    'referrals': 'الإحالة',
    'code': 'الكود',
    'share': 'مشاركة',
    'totalReferrals': 'إجمالي الإحالات',
    'activeReferrals': 'الإحالات النشطة',
    'earnings': 'الرصيد',
    'pointsHistory': 'سجل الرصيد',
    'insufficientPoints': 'رصيد غير كافٍ',
    'claim': 'المطالبة',
    'claimAll': 'المطالبة بكل شيء',
    'reload': 'إعادة التحميل',
    'loading': 'جارٍ التحميل...',
    'error': 'خطأ',
    'ok': 'موافق',
    'cancel': 'إلغاء',
    'yes': 'نعم',
    'no': 'لا',
    'enterAmount': 'أدخل المبلغ',
    'skip': 'تخطي',
    'next': 'التالي',
    'finish': 'إنهاء',
    'welcome': 'مرحباً بك في هامر بوينتس',
    'welcomeDescription': 'اجمع عملة ITC من المهام واشترِ الحيوانات الافتراضية',
    'earnPoints': 'اجمع ITC',
    'buyAnimals': 'اشترِ الحيوانات',
    'chicken': 'دجاجة',
    'cow': 'بقرة',
    'dog': 'كلب',
    'horse': 'حصان',
    'elephant': 'فيل',
    'dragon': 'تنين',
    'dailyProfit': 'ITC يومية',
    'collectEvery': 'يجمع كل',
    'hours': 'ساعات',
    'day': 'يوم',
    'profitPerHour': 'ITC في الساعة',
    'totalProfit': 'إجمالي الربح',
    'purchaseConfirmed': 'تم الشراء بنجاح',
    'pointsWillBeAdded': 'سيتم إضافة ITC إلى محفظتك',
    'dailyLoginStreak': 'عدد مرات تسجيل الدخول المتتالي',
    'loginToday': 'تسجيل الدخول اليوم',
    'claimToday': 'المطالبة اليوم',
    'todayEarnings': 'ربح اليوم',
    'weeklyEarnings': 'ربح الأسبوع',
    'totalEarnings': 'إجمالي الربح',
    'completed': 'مكتمل',
    'inProgress': 'قيد التنفيذ',
    'notCompleted': 'لم يكتمل',
    'survey': 'استطلاع',
    'download': 'تحميل',
    'ad': 'إعلان',
    'social': 'اجتماعي',
    'visit': 'زيارة',
    'now': 'الآن',
    'remaining': 'المتبقي',
    'getPoints': 'احصل على ITC',
    'playNow': 'العب الآن',
    'claimReward': 'المطالبة بالمكافأة',
    'shareApp': 'شارك التطبيق',
    'inviteFriends': 'ادعُ أصدقاءك',
    'earnTogether': 'اجمعوا معاً',
    'specialEvents': 'الأحداث الخاصة',
    'bonusPoints': 'مكافأة ITC',
    'extraEarnings': 'ربح إضافي',
    'specialOffers': 'عروض خاصة',
  };
}
